COMMON:
    RUN_NAME: gmm_to_gff_testing_filterPSL_100bp
    OUT_DIR: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/pipeline_runs"
    MAIN_SPECIES: "Glossina fuscipes fuscipes"



# ---------------- PREP ----------------------
MAKE_OOC:
    GENOME: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/Glossina-fuscipes-IAEA_SCAFFOLDS_GfusI1.renamed.fa"
    OLIGO_LEN: 11

# ---------------- PREP ----------------------
RUN_BLAT:
    TRANSCRIPTS: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/transcripts.fa"
    PSL_NAME: "gmm_transcripts_v_GfusI1_scaffold.dna2dna.psl"
# ---------------- PREP ----------------------
# GTF_JUST_EXONS:
#     GTF_PATH: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/pipeline_prep/Glossina-fuscipes-IAEA_BASEFEATURES_GfusI1.3.gtf"

# ---------------- PREP ----------------------
GTF_TO_BED:
    GTF: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/Glossina-fuscipes-IAEA_BASEFEATURES_GfusI1.3.gtf"



# ---------------- MAIN ----------------------
ANNOTATIONS_VIA_FASTA:
    TX_FASTA: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/transcripts.fa"
    ORTHOLOG_TABLE: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/vectorbase_orthologs_GMOY_GFUI.csv"

# ---------------- MAIN ----------------------
FILTER_PSL_TO_BED:
    # PSL: # this will be defned in rule: run_blat
    BED_FROM_PSL_COVERAGE: 0.90
    BED_FROM_PSL_QSIZE: 100

# ---------------- MAIN ----------------------
SUBTRACT_GENE_MODELS:
    # GENE_MODELS_BED: # stored in rules.gtf_to_bed.output.bed

# ---------------- MAIN ----------------------
MAKE_SNP_BEDS:
    DO_CLEANING: True
    P_THRESH: 0.05
    SCAFFOLD_NAME_MAP: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/contig_name_length.csv"
    SNP_FILES:
        - "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/snp_list_OT_1_with_p_value.txt"
        - "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/snp_list_MS_1_with_p_value.txt"
        - "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/snp_list_NB_1_with_p_value.txt"
        - "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/snp_list_afterFS_with_p_value_LD_1.txt"

# ---------------- MAIN ----------------------
GET_NEAREST_K_FEATURES:
    K: 10

# ---------------- MAIN ----------------------
MAKE_ID_TABLE_NO_DIFF_EXPR:
    CUFFCMP_TRACKING: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/cuffcmp.tracking"

# ---------------- MAIN ----------------------
MAKE_ID_TABLE_WITH_DIFF_EXPR:
    EDGER_RESULTS_INFO:
        CONGO: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/Congo.edgeR.anno.txt"
        MIDGUT: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/midgut.edgeR.anno.txt"
        PB: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/PB.edgeR.anno.txt"
        PV_PLUS_MINUS: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/PV_Plus_Minus.edgeR.anno.txt"
        PV_PLUS_PLUS: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/PV_Plus_Plus.edgeR.anno.txt"
        SG: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/SG.edgeR.anno.txt"
    CUFFLINKS_RESULTS_INFO:
        CONGO: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/Congo.cuffdiff.txt"
        MIDGUT: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/midgut.cuffdiff.txt"
        PB: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/PB.cuffdiff.txt"
        PV_PLUS_MINUS: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/PV_Plus_Minus.cuffdiff.txt"
        PV_PLUS_PLUS: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/PV_Plus_Plus.cuffdiff.txt"
        SG: "/home/gus/MEGAsync/zim/main/Yale/Collaborations/Hongyu-tsetse/gmm_to_gff_pipeline/external_files/SG.cuffdiff.txt"
# ---------------- MAIN ----------------------
SNPS_NEAR_HOMOLOGOUS_DE:
    SNP_DISTANCE_FROM_GENE: 0
    DE_TABLE_CHUNKSIZE: 1000
    RUN_PARALLEL: "yes"
    GENOME_BROWSER_URL: https://www.vectorbase.org/Glossina_fuscipes/Location/View?r=[chrom]:[left]-[right]
